/** All possible task states */
export type TaskStatus =
  | 'draft'
  | 'pending'
  | 'running'
  | 'success'
  | 'failed'
  | 'cancelled'
  | 'compensating'
  | 'compensated'
  | 'manual-review';

/** Subscription tier required */
export type TaskTier = 'free' | 'lite' | 'plus' | 'pro' | 'ultra';

/** Task class per spec §11.2 */
export type TaskClass = 'reminder' | 'recurring' | 'monitoring';

/** Parsed schedule for a task */
export interface TaskSchedule {
  cron?: string;
  fireAt?: string;
}

/** A scheduled task definition */
export interface Task {
  id: string;
  type: string;
  title: string;
  description: string;
  cron?: string;
  class?: TaskClass;
  schedule?: TaskSchedule;
  nextRunAt?: string;
  monitoringUrl?: string;
  status: TaskStatus;
  tierRequired: TaskTier;
  createdAt: string;
  updatedAt: string;
  dependsOn?: string[];
  parentTaskId?: string;
  sourceRefs?: string[];
  projectId?: string;
  recurrence?: string;
  agentId?: string;
  /** Fuel mode for server-fired runs ('local' | 'managed' | 'byok'). */
  fuelMode?: 'local' | 'managed' | 'byok';
}

/** A single execution record of a task */
export interface TaskRun {
  id: number;
  taskId: string;
  status: 'running' | 'success' | 'failed';
  output?: string;
  runAt: string;
  completedAt?: string;
  error?: string;
}

/** Draft generated by the AI from plain-language input */
export interface TaskDraft {
  when: string;
  read: string;
  do: string;
  tell: string;
  uses: string[];
}
