/**
 * Capability registry + model catalog loader (architecture §8.3).
 *
 * Source of truth is generated by `scripts/update-model-catalog.mjs` from
 * pi.dev and bundled as `model-catalog.generated.json`. At runtime we prefer a
 * remote-refreshed copy (fetched from the Worker `/v1/catalog/models` route,
 * cached by the app), falling back to the bundled snapshot when offline or on
 * first launch.
 *
 * Memory note (4 GB Android target): the bundled JSON is parsed once and cached
 * in-module. Consumers query by provider id so we never hold more than the
 * single parsed object; no per-model allocation on the hot path.
 */

import bundled from './generated/model-catalog.generated.json' with { type: 'json' };

export type ModelInputModality = 'text' | 'image' | 'audio' | 'video';

export interface ModelCapabilities {
  id: string;
  name: string;
  contextWindow: number | null;
  maxTokens: number | null;
  reasoning: boolean;
  input: ModelInputModality[];
  cost?: { input: number | null; output: number | null };
}

export interface ProviderModels {
  models: ModelCapabilities[];
}

export interface ModelCatalog {
  version: string;
  generatedAt: string;
  source: string;
  providerCount: number;
  modelCount: number;
  providers: Record<string, ProviderModels>;
}

const BUNDLED = bundled as unknown as ModelCatalog;

/** Currently active catalog — starts bundled, replaced by remote refresh. */
let active: ModelCatalog = BUNDLED;

/** Replace the active catalog with a remotely-fetched one (validated shape). */
export function setModelCatalog(next: unknown): boolean {
  if (!isValidCatalog(next)) return false;
  // Only accept a remote catalog that is at least as fresh as the bundled one.
  if (next.version < BUNDLED.version) return false;
  active = next;
  return true;
}

export function getModelCatalog(): ModelCatalog {
  return active;
}

export function getBundledCatalogVersion(): string {
  return BUNDLED.version;
}

/** Chat-capable models for a provider id (empty array if unknown). */
export function getModelsForProvider(providerId: string): ModelCapabilities[] {
  return active.providers[providerId]?.models ?? [];
}

/** Capability lookup for a single model within a provider. */
export function getModelCapabilities(
  providerId: string,
  modelId: string,
): ModelCapabilities | null {
  const models = active.providers[providerId]?.models;
  if (!models) return null;
  return models.find((m) => m.id === modelId) ?? null;
}

/** Does this provider/model support reasoning tokens? */
export function modelSupportsReasoning(providerId: string, modelId: string): boolean {
  return getModelCapabilities(providerId, modelId)?.reasoning ?? false;
}

/** Does this provider/model accept image input (for vision routing)? */
export function modelSupportsVision(providerId: string, modelId: string): boolean {
  return getModelCapabilities(providerId, modelId)?.input.includes('image') ?? false;
}

function isValidCatalog(v: unknown): v is ModelCatalog {
  if (!v || typeof v !== 'object') return false;
  const c = v as Partial<ModelCatalog>;
  return (
    typeof c.version === 'string' &&
    typeof c.providers === 'object' &&
    c.providers !== null
  );
}
